name: GitHub Actions self hosted runner

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Verify Python & Pip
        run:
          python3 --version
          python3 -m ensurepip --upgrade || true
          apt install python3-pip

      - name: Install dependencies
        run: 
          pip install pytest

      - name: Run tests
        run:
          cd src
          python3 -m pytest addition.py
