name: GitHub Actions self hosted runner

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: install pip
        run: sudo apt install python3-full python3-pip -y
  
      - name: Install dependencies
        run: 
          sudo apt install python3-pytest -y

      - name: Run tests
        run:
          cd src && pytest addition.py
