name: GitHub Actions self hosted runner

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: install pip
        run: apt install python3-full python3-pip
  
      - name: Install dependencies
        run: 
          python3 -m pip install pytest

      - name: Run tests
        run:
          cd src
          python3 -m pytest addition.py
